definitions:
  config:
    /hippo:namespaces/myproject/productCompound:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 0a4dd94c-0dc8-4643-b517-9c26d291b199
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: c496f719-d455-47e4-aa59-bd0e94b431aa
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: 601dacd6-c67c-48b5-ab49-a846d5119fc6
          hipposysedit:node: true
          hipposysedit:supertype: ['hippo:compound', 'hippostd:relaxed']
          hipposysedit:uri: http://www.myproject.com/myproject/nt/1.0
          /productPicker:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myproject:productPicker
            hipposysedit:primary: false
            hipposysedit:type: OpenUiString
            hipposysedit:validators: [required]
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: myproject:productCompound
          myproject:productPicker: ''
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /productPicker:
            jcr:primaryType: frontend:plugin
            caption: Product Picker
            field: productPicker
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              ui.extension: commerceProductPicker
