definitions:
  config:
    /hippo:namespaces/myproject/ProductDetailCustomContent:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 8698159f-4fbc-41e5-9255-f3e6db3d129e
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 1fdf8d89-ff39-44e7-8910-102d68410928
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: 816fd32f-e9f0-4858-82dc-b09584063fef
          hipposysedit:node: true
          hipposysedit:supertype: ['myproject:basedocument', 'hippostd:relaxed', 'hippotranslation:translated']
          hipposysedit:uri: http://www.myproject.com/myproject/nt/1.0
          /productDetailCustomContentCompounds:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: myproject:productDetailCustomContentCompounds
            hipposysedit:primary: false
            hipposysedit:type: myproject:ProductDetailCustomContentCompound
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: myproject:ProductDetailCustomContent
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: d801698b-c549-4975-92f8-1e5bde9ae7cd
          hippostdpubwf:lastModificationDate: 2021-10-15T10:56:49.377-04:00
          hippostdpubwf:creationDate: 2021-10-15T10:56:49.377-04:00
          /myproject:productDetailCustomContentCompounds:
            jcr:primaryType: myproject:ProductDetailCustomContentCompound
            myproject:tabLabel: ''
            /myproject:tabContent:
              jcr:primaryType: hippostd:html
              hippostd:content: ''
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /productDetailCustomContentCompounds:
            jcr:primaryType: frontend:plugin
            caption: Product Detail Custom Content
            field: productDetailCustomContentCompounds
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
