definitions:
  config:
    /hst:hst/hst:configurations:
      /common:
        jcr:primaryType: hst:configuration
        /hst:sitemap:
          jcr:primaryType: hst:sitemap
        /hst:abstractpages:
          jcr:primaryType: hst:pages
        /hst:pages:
          jcr:primaryType: hst:pages
        /hst:components:
          jcr:primaryType: hst:components
        /hst:templates:
          jcr:primaryType: hst:templates
        /hst:sitemenus:
          jcr:primaryType: hst:sitemenus
        /hst:sitemapitemhandlers:
          jcr:primaryType: hst:sitemapitemhandlers
        /hst:catalog:
          jcr:primaryType: hst:catalog
          /common-catalog:
            jcr:primaryType: hst:containeritempackage
            /SlickSlider:
              jcr:primaryType: hst:componentdefinition
              hst:componentclassname: org.hippoecm.hst.component.support.bean.dynamic.BaseHstDynamicComponent
              hst:ctype: SlickSlider
              hst:iconpath: images/essentials/catalog-component-icons/352200_carousel_view_icon.svg
              hst:label: Slick Slider
              hst:xtype: hst.vbox
              hst:fieldgroups.Slider Settings: [arrows, autoplay, autoplaySpeed, dots,
                dotsStyle, fade, infinite, pauseOnDotsHover, pauseOnFocus, pauseOnHover,
                rows, slidesPerRow, slidesToShow, slidesToScroll, vertical]
              hst:fieldgroups: [Slides, Slider Settings]
              hst:fieldgroups.Slides: [document]
              /document:
                jcr:primaryType: hst:dynamicparameter
                hst:valuetype: text
                hst:displayname: Slides
                hst:required: true
                /hst:fieldconfig:
                  jcr:primaryType: hst:jcrpath
                  hst:pickerconfiguration: cms-pickers/documents-only
                  hst:relative: true
              /arrows:
                jcr:primaryType: hst:dynamicparameter
                hst:valuetype: boolean
                hst:displayname: Arrows
                hst:defaultvalue: 'true'
              /autoplay:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'false'
                hst:displayname: Autoplay
                hst:valuetype: boolean
              /autoplaySpeed:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: '3000'
                hst:displayname: Autoplay Speed
                hst:valuetype: integer
              /dots:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'true'
                hst:displayname: Dots
                hst:valuetype: boolean
              /fade:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'false'
                hst:displayname: Fade
                hst:valuetype: boolean
              /infinite:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'true'
                hst:displayname: Infinite
                hst:valuetype: boolean
              /pauseOnDotsHover:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'false'
                hst:displayname: Pause On Dots Hover
                hst:valuetype: boolean
              /pauseOnFocus:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'false'
                hst:displayname: Pause On Focus
                hst:valuetype: boolean
              /pauseOnHover:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'false'
                hst:displayname: Pause On Hover
                hst:valuetype: boolean
              /rows:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: '1'
                hst:displayname: Rows
                hst:valuetype: integer
              /slidesPerRow:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: '1'
                hst:displayname: Slides Per Row
                hst:valuetype: integer
              /slidesToScroll:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: '1'
                hst:displayname: Slides To Scroll
                hst:valuetype: integer
              /slidesToShow:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: '1'
                hst:displayname: Slides To Show
                hst:valuetype: integer
              /vertical:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'false'
                hst:displayname: Vertical
                hst:valuetype: boolean
              /dotsStyle:
                jcr:primaryType: hst:dynamicparameter
                hst:displayname: Dots Style
                hst:valuetype: text
                hst:defaultvalue: dots
                /hst:fieldconfig:
                  jcr:primaryType: hst:dropdown
                  hst:sourceid: dotsStyle
            /FlexibleGrid:
              jcr:primaryType: hst:componentdefinition
              hst:componentclassname: org.hippoecm.hst.component.support.bean.dynamic.BaseHstDynamicComponent
              hst:ctype: FlexibleGrid
              hst:iconpath: images/essentials/catalog-component-icons/banner.svg
              hst:label: Flexible Grid
              hst:xtype: hst.vbox
              /document:
                jcr:primaryType: hst:dynamicparameter
                hst:displayname: Document
                hst:required: true
                hst:valuetype: text
                /hst:fieldconfig:
                  jcr:primaryType: hst:jcrpath
                  hst:pickerconfiguration: cms-pickers/documents-only
                  hst:relative: true
              /itemsPerRow:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: '3'
                hst:displayname: Items Per Row
                hst:valuetype: integer
            /CategorySlider:
              jcr:primaryType: hst:componentdefinition
              hst:componentclassname: org.hippoecm.hst.component.support.bean.dynamic.BaseHstDynamicComponent
              hst:ctype: CategorySlider
              hst:fieldgroups: [Slides, Slider Settings]
              hst:fieldgroups.Slider Settings: [arrows, autoplay, autoplaySpeed, dots,
                dotsStyle, fade, infinite, pauseOnDotsHover, pauseOnFocus, pauseOnHover,
                rows, slidesPerRow, slidesToShow, slidesToScroll, vertical]
              hst:fieldgroups.Slides: [document]
              hst:iconpath: images/essentials/catalog-component-icons/352200_carousel_view_icon.svg
              hst:label: Category Slider
              hst:xtype: hst.vbox
              /document:
                jcr:primaryType: hst:dynamicparameter
                hst:displayname: Categories Document
                hst:required: true
                hst:valuetype: text
                /hst:fieldconfig:
                  jcr:primaryType: hst:jcrpath
                  hst:pickerconfiguration: cms-pickers/documents-only
                  hst:relative: true
              /arrows:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'true'
                hst:displayname: Arrows
                hst:valuetype: boolean
              /autoplay:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'false'
                hst:displayname: Autoplay
                hst:valuetype: boolean
              /autoplaySpeed:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: '3000'
                hst:displayname: Autoplay Speed
                hst:valuetype: integer
              /dots:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'true'
                hst:displayname: Dots
                hst:valuetype: boolean
              /fade:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'false'
                hst:displayname: Fade
                hst:valuetype: boolean
              /infinite:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'true'
                hst:displayname: Infinite
                hst:valuetype: boolean
              /pauseOnDotsHover:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'false'
                hst:displayname: Pause On Dots Hover
                hst:valuetype: boolean
              /pauseOnFocus:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'false'
                hst:displayname: Pause On Focus
                hst:valuetype: boolean
              /pauseOnHover:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'false'
                hst:displayname: Pause On Hover
                hst:valuetype: boolean
              /rows:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: '1'
                hst:displayname: Rows
                hst:valuetype: integer
              /slidesPerRow:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: '1'
                hst:displayname: Slides Per Row
                hst:valuetype: integer
              /slidesToScroll:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: '1'
                hst:displayname: Slides To Scroll
                hst:valuetype: integer
              /slidesToShow:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: '1'
                hst:displayname: Slides To Show
                hst:valuetype: integer
              /vertical:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'false'
                hst:displayname: Vertical
                hst:valuetype: boolean
              /dotsStyle:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: dots
                hst:displayname: Dots Style
                hst:valuetype: text
                /hst:fieldconfig:
                  jcr:primaryType: hst:dropdown
                  hst:sourceid: dotsStyle
            /ProductSlider:
              jcr:primaryType: hst:componentdefinition
              hst:componentclassname: org.hippoecm.hst.component.support.bean.dynamic.BaseHstDynamicComponent
              hst:ctype: ProductSlider
              hst:fieldgroups: [Products, Slider Settings]
              hst:fieldgroups.Slider Settings: [arrows, autoplay, autoplaySpeed, dots,
                dotsStyle, fade, infinite, pauseOnDotsHover, pauseOnFocus, pauseOnHover,
                rows, slidesPerRow, slidesToShow, slidesToScroll, vertical]
              hst:fieldgroups.Slides: [document]
              hst:iconpath: images/essentials/catalog-component-icons/352200_carousel_view_icon.svg
              hst:label: Product Slider
              hst:xtype: hst.vbox
              /document:
                jcr:primaryType: hst:dynamicparameter
                hst:displayname: Slides
                hst:required: true
                hst:valuetype: text
                /hst:fieldconfig:
                  jcr:primaryType: hst:jcrpath
                  hst:pickerconfiguration: cms-pickers/documents-only
                  hst:relative: true
              /arrows:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'true'
                hst:displayname: Arrows
                hst:valuetype: boolean
              /autoplay:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'false'
                hst:displayname: Autoplay
                hst:valuetype: boolean
              /autoplaySpeed:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: '3000'
                hst:displayname: Autoplay Speed
                hst:valuetype: integer
              /dots:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'true'
                hst:displayname: Dots
                hst:valuetype: boolean
              /fade:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'false'
                hst:displayname: Fade
                hst:valuetype: boolean
              /infinite:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'true'
                hst:displayname: Infinite
                hst:valuetype: boolean
              /pauseOnDotsHover:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'false'
                hst:displayname: Pause On Dots Hover
                hst:valuetype: boolean
              /pauseOnFocus:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'false'
                hst:displayname: Pause On Focus
                hst:valuetype: boolean
              /pauseOnHover:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'false'
                hst:displayname: Pause On Hover
                hst:valuetype: boolean
              /rows:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: '1'
                hst:displayname: Rows
                hst:valuetype: integer
              /slidesPerRow:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: '1'
                hst:displayname: Slides Per Row
                hst:valuetype: integer
              /slidesToScroll:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: '1'
                hst:displayname: Slides To Scroll
                hst:valuetype: integer
              /slidesToShow:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: '1'
                hst:displayname: Slides To Show
                hst:valuetype: integer
              /vertical:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: 'false'
                hst:displayname: Vertical
                hst:valuetype: boolean
              /dotsStyle:
                jcr:primaryType: hst:dynamicparameter
                hst:defaultvalue: dots
                hst:displayname: Dots Style
                hst:valuetype: text
                /hst:fieldconfig:
                  jcr:primaryType: hst:dropdown
                  hst:sourceid: dotsStyle
      /myproject:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
      /react:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
