definitions:
  config:
    /hst:hst/hst:configurations/vue/hst:abstractpages/base:
      jcr:primaryType: hst:component
      hst:template: base-layout
      /menu:
        jcr:primaryType: hst:component
        hst:componentclassname: com.myproject.components.MenuItemBanners
        hst:parameternames: [selectedMenu, level, menu]
        hst:parametervalues: ['on', '1', main]
        hst:template: base-top-menu
      /footer:
        jcr:primaryType: hst:component
        hst:template: base-footer
        /container:
          jcr:primaryType: hst:containercomponentreference
          hst:referencecomponent: base/footer
