/content/documents/react/product-detail-custom-content:
  .meta:order-before: page-content
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 561e1fcb-b8f2-4c3f-a0b0-93600b0dc367
  hippo:name: Product Detail Custom Content
  hippostd:foldertype: [new-ProductDetailCustomContent-document]
  hippotranslation:id: bea1e7c7-9ee5-49d2-802d-332e21aa25a8
  hippotranslation:locale: en
  /80123fam:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: e6f9410c-a2fd-415e-9327-098b5228dc75
    hippo:versionHistory: b614ff90-d191-479e-9ff3-8c8398ec6cdd
    /80123fam[1]:
      jcr:primaryType: myproject:ProductDetailCustomContent
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: de3257e2-16b8-4bea-93b1-d4e438230907
      hippo:availability: []
      hippostd:retainable: false
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2022-01-19T10:20:07.110-05:00
      hippostdpubwf:lastModificationDate: 2022-01-19T10:21:09.232-05:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 66aa057c-d36f-4ab8-a788-b555cceceb0d
      hippotranslation:locale: en
      /myproject:productDetailCustomContentCompounds[1]:
        jcr:primaryType: myproject:ProductDetailCustomContentCompound
        myproject:tabLabel: Description
        /myproject:tabContent:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <h2>This is a heading</h2>

            <p>This is some text.</p>
      /myproject:productDetailCustomContentCompounds[2]:
        jcr:primaryType: myproject:ProductDetailCustomContentCompound
        myproject:tabLabel: Care Instructions
        /myproject:tabContent:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <h2>This is another heading</h2>

            <p>This is some other text.</p>

            <p>&nbsp;</p>
    /80123fam[2]:
      jcr:primaryType: myproject:ProductDetailCustomContent
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: 541db619-29d8-492e-902a-cabf586345d7
      hippo:availability: [preview]
      hippostd:retainable: false
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2022-01-19T10:20:07.110-05:00
      hippostdpubwf:lastModificationDate: 2022-01-19T10:21:22.532-05:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 66aa057c-d36f-4ab8-a788-b555cceceb0d
      hippotranslation:locale: en
      /myproject:productDetailCustomContentCompounds[1]:
        jcr:primaryType: myproject:ProductDetailCustomContentCompound
        myproject:tabLabel: Description
        /myproject:tabContent:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <h2>This is a heading</h2>

            <p>This is some text.</p>
      /myproject:productDetailCustomContentCompounds[2]:
        jcr:primaryType: myproject:ProductDetailCustomContentCompound
        myproject:tabLabel: Care Instructions
        /myproject:tabContent:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <h2>This is another heading</h2>

            <p>This is some other text.</p>

            <p>&nbsp;</p>
    /80123fam[3]:
      jcr:primaryType: myproject:ProductDetailCustomContent
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 69d1dca5-d4c5-45c8-883e-510023223350
      hippo:availability: [live]
      hippostd:retainable: false
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2022-01-19T10:20:07.110-05:00
      hippostdpubwf:lastModificationDate: 2022-01-19T10:21:22.532-05:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2022-01-19T10:21:24.013-05:00
      hippotranslation:id: 66aa057c-d36f-4ab8-a788-b555cceceb0d
      hippotranslation:locale: en
      /myproject:productDetailCustomContentCompounds[1]:
        jcr:primaryType: myproject:ProductDetailCustomContentCompound
        myproject:tabLabel: Description
        /myproject:tabContent:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <h2>This is a heading</h2>

            <p>This is some text.</p>
      /myproject:productDetailCustomContentCompounds[2]:
        jcr:primaryType: myproject:ProductDetailCustomContentCompound
        myproject:tabLabel: Care Instructions
        /myproject:tabContent:
          jcr:primaryType: hippostd:html
          hippostd:content: |-
            <h2>This is another heading</h2>

            <p>This is some other text.</p>

            <p>&nbsp;</p>
