definitions:
  config:
    /hst:hst/hst:configurations/react/hst:components/ProductGridCategory:
      jcr:primaryType: hst:component
      hst:parameternames: [categoryId]
      hst:parametervalues: ['${1}']
