definitions:
  config:
    /hst:hst/hst:configurations/vue/hst:components/ProductDetail:
      jcr:primaryType: hst:component
      hst:parameternames: [productCode]
      hst:parametervalues: ['${1}']
